### ISSUE TITLE
error with vue 2.5.3

### ISSUE THREAD

**Issue by mrfarhadir** [dyonir/vue2-persian-datepicker#10]
Hi, Thanks for this component I faced with problem when I use this with vue version 2.5.3 and vuetifyjs version 0.17.3
here is the screenshot : 
![image](https://user-images.githubusercontent.com/26628753/33703078-bb8cd776-db3b-11e7-84cd-719060a04187.png)

**Comment by rhajizadeh** [comment]
Please send your code or at least part of it, you wrote for this page.

**Comment by mrfarhadir** [comment]
solved !
