### ISSUE TITLE
month is gone after jumping to the next year

### ISSUE THREAD

**Issue by beigiz** [dyonir/vue2-persian-datepicker#11]
hi, I did implement the structure of your component just like the doc,
when I just go from 'اسفند' of 139x to the next year, there is no change in the year (remains on 139x) and the month title is gone!
with no error is thrown
check the image I sent
thank you very much for your component  
![2017-12-09](https://user-images.githubusercontent.com/23187274/33791096-46df73fe-dc9c-11e7-9d5e-90e65a1d4e7c.png)

**Comment by rhajizadeh** [comment]
Hello
sorry for delay
which version are you using?

**Comment by beigiz** [comment]
according to npm list :  vue2-persian-datepicker@1.4.0

**Comment by rhajizadeh** [comment]
Is anything showing up in console? If yes please send it.

**Comment by rhajizadeh** [comment]
The version you are using is old.
Please upgrade to latest version which is 1.5.29.
1.4.0 had that issue and I fixed it.

**Comment by beigiz** [comment]
thanks a lot!
it's working fine now
