### ISSUE TITLE
How Get selected date

### ISSUE THREAD

**Issue by mariajhn** [dyonir/vue2-persian-datepicker#17]
Hi,
I want to use your datepicker, but I want to extract year, month and day from the selected date.
Could you please help me?!

Thnks

**Comment by rhajizadeh** [comment]
Unfortunately it is not possible right now.
For the time being you can split selected date with '/'
But this feature will be added.

**Comment by rhajizadeh** [comment]
Upgrade to latest version. Now you can listen to selected event, and use it's input parameter for getting year, month and day.

**Comment by rhajizadeh** [comment]
Try this fiddle:
[https://jsfiddle.net/rh2020/zjezzfdk/](url)

**Comment by mariajhn** [comment]
I try this code but nothing happened !?
I have another question, 
I want to write this code when a date is selected:
`myDate=date`
where myDate is a variable in a controller.
Is it possible?
Thanks in advance.

**Comment by rhajizadeh** [comment]
Yes it is possible. Use parentheses function definition. 
`v-on:selected="(date) => {this.visitDate = date;}"`
