### ISSUE TITLE
Error with vue

### ISSUE THREAD

**Issue by mariajhn** [dyonir/vue2-persian-datepicker#18]
Hi,
I write this code :
` <pdatepicker v-model='date'  inline-mode=true  ></pdatepicker> `

When running this code, the following error happened: 

**[Vue warn]: Invalid prop: type check failed for prop "inlineMode". Expected Boolean, got String.**

How can I solve it?!

**Comment by rhajizadeh** [comment]
Test this:
`<pdatepicker` v-model='date' inline-mode='true' ></pdatepicker>

**Comment by mariajhn** [comment]
Thnks for your reply,
I try both codes, but the problem does not fix :(
