### ISSUE TITLE
Wrong dates

### ISSUE THREAD

**Issue by farzadso** [dyonir/vue2-persian-datepicker#19]
The datepicker provides wrong dates. For instance "Esfand" is a 29-day month this year. But your datepicker shows 30 days which is wrong. It also shows the same for the year 1394.

**Comment by rhajizadeh** [comment]
Thank you for informing me.
I fixed leap year bug in the last release.
Please tell me if you found anything else

**Comment by farzadso** [comment]
Thanks for following up on the bug.

When do you think you will issue a release?

**Comment by farzadso** [comment]
Thanks for the followup. 

I will give it a go and let you know of the result.

Cheers.

**Comment by farzadso** [comment]
Just tested it. Seems to be ok. Thanks
