### ISSUE TITLE
Show current date in textbox

### ISSUE THREAD

**Issue by aebrs** [dyonir/vue2-persian-datepicker#27]
Hi,
Is it possible to show current date in text box initially?
Is it possible to use this as date converter  to/from Jalali to Georgian?
Thanks in advance.

**Comment by rhajizadeh** [comment]
Yes these are good features to add

**Comment by rhajizadeh** [comment]
@aebrs  I recommend using [moment-jalaali](https://momentjs.com/docs/#/plugins/jalaali/) and in near future this component will start using that for conversion as well.

**Comment by rhajizadeh** [comment]
Although I said that we will have this features but now they seem redundant. You can just the variable of v-model you are passing to component to today's date
