### ISSUE TITLE
Date formatting not work properly

### ISSUE THREAD

**Issue by MINASHIJ** [dyonir/vue2-persian-datepicker#28]
hi and thanks for your greate library.
I change the Date formatting, in input i see the Date formatting that i used, but the value is not the same , and is in 'yyyy/M/d' format.
for example i use this: 
<pdatepicker v-model='date' format-date='yyyy/MMM/dd' ></pdatepicker>
but "this.followdate" value is in  'yyyy/M/d' format
for more information , i select date and it shows : ۱۳۹۷/۰۴/۰۲
but the input value is: ۱۳۹۷/۴/۲
please help me, i need to solve this problem.

**Comment by rhajizadeh** [comment]
Hi
take a look at [this fiddle](https://jsfiddle.net/rh2020/zjezzfdk/80/). according to this formatting is working properly.
If this fiddle wouldn't solve your problem please provide more of your code so I could figure what is wrong.

**Comment by MINASHIJ** [comment]
may i type in farsi?

**Comment by MINASHIJ** [comment]
please see this page : https://dyonir.github.io/vue2-persian-datepicker/
تاریخ انتخاب شده  is always in " yyyy/M/d " format.
but i need to be in "yyyy/MM/dd" format.

**Comment by rhajizadeh** [comment]
Yeap sure, type in Persian

**Comment by rhajizadeh** [comment]
متوجه نشدم
مشکلتون چی هست؟
تو صفحه دمو همه چیز با فرمت
yyyy/MM/dd 
هست
