### ISSUE TITLE
خطای وابستگی

### ISSUE THREAD

**Issue by amirh95** [dyonir/vue2-persian-datepicker#3]
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Projects/xxx/node_modules/vue2-persian-datepicker/.babelrc" at 0, attempted to resolve relative to "/Projects/xxx/node_modules/vue2-persian-datepicker"

**Comment by rhajizadeh** [comment]
this issue will be fixed in the next release but for now you can fix it buy this npm commands:

```bash
npm install --save-dev babel-plugin-transform-runtime
npm install --save-dev babel-preset-stage-2
```
