### ISSUE TITLE
Set start and end date

### ISSUE THREAD

**Issue by hatrena** [dyonir/vue2-persian-datepicker#6]
Hi, is there anyway that i can set or defin start and end date? and also disabling year and month change?

**Comment by sajad-kioumarsi** [comment]
and also prevent selecting past dates

**Comment by rhajizadeh** [comment]
> and also prevent selecting past dates
Hi Sajad. You can pass minimum year to prevent user from selecting pass dates

**Comment by rhajizadeh** [comment]
> is there anyway that i can set or defin start and end date? 

Hi
I am planning to add daterange in the next release

> also disabling year and month change

Right now it is now possible. I will also add this feature to the next release.

**Comment by rhajizadeh** [comment]
@sajad-kioumarsi 
The solution I mentioned earlier will actually start datepicker from certain date.
I will add disabled dates to picker

**Comment by rhajizadeh** [comment]
@sajad-kioumarsi Can you please open a new issue for your suggestion?

**Comment by rhajizadeh** [comment]
#7 created for disabled dates
