### ISSUE TITLE
nuxt.js support

### ISSUE THREAD

**Issue by davodaslanifakor** [dyonir/vue2-persian-datepicker#9]
من اضافه کردم به پروژه nuxt  پیغام خطا میده

![image](https://user-images.githubusercontent.com/14367811/33483094-6012cb14-d6b1-11e7-9da7-01f46a748387.png)

چه کاری برای لود شدنش تو nuxt انجام بدم

**Comment by rhajizadeh** [comment]
Sorry for delay
I'll check that...
